#!/usr/bin/env bash
# =============================================================================
# deploy.sh — Phase 6: Frontend build + S3 upload + CloudFront invalidation
# =============================================================================
#
# Usage:
#   ./scripts/deploy.sh [dev|prod]
#
# What it does:
#   1. Reads Terraform outputs (bucket name, CF distribution ID, API URL)
#   2. Writes frontend/.env.production with the real API URL
#   3. Builds the Vue 3 app with `npm run build`
#   4. Syncs dist/ to the S3 frontend bucket
#   5. Invalidates the CloudFront cache (index.html + hashed assets)
#
# Prerequisites:
#   - AWS CLI configured (profile: metads)
#   - Terraform already applied (infra/ state exists)
#   - Node.js + npm installed (for frontend build)
#   - VITE_CLERK_PUBLISHABLE_KEY exported in the shell, e.g.:
#       export VITE_CLERK_PUBLISHABLE_KEY=pk_test_...
#     or set manually in frontend/.env.production after running this script.
#
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
INFRA_DIR="${SCRIPT_DIR}/../infra"
FRONTEND_DIR="${REPO_ROOT}/frontend"

ENV="${1:-dev}"

if [[ "${ENV}" != "dev" && "${ENV}" != "prod" ]]; then
  echo "ERROR: environment must be 'dev' or 'prod' (got '${ENV}')"
  exit 1
fi

TFVARS_FILE="${INFRA_DIR}/${ENV}.tfvars"
AWS_PROFILE="metads"

echo "============================================="
echo "  MetaAds frontend deploy — env: ${ENV}"
echo "============================================="

# ---------------------------------------------------------------------------
# Step 1: Read Terraform outputs
# ---------------------------------------------------------------------------

echo ""
echo "[1/5] Reading Terraform outputs..."

cd "${INFRA_DIR}"

FRONTEND_BUCKET=$(terraform output -raw frontend_bucket_name 2>/dev/null)
CF_DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id 2>/dev/null)
API_GATEWAY_URL=$(terraform output -raw api_gateway_url 2>/dev/null)
FRONTEND_URL=$(terraform output -raw frontend_url 2>/dev/null)

if [[ -z "${FRONTEND_BUCKET}" || -z "${CF_DISTRIBUTION_ID}" || -z "${API_GATEWAY_URL}" ]]; then
  echo "ERROR: Terraform outputs are empty. Have you run 'terraform apply' yet?"
  echo "  cd infra && terraform apply -var-file=${ENV}.tfvars"
  exit 1
fi

echo "  S3 bucket:            ${FRONTEND_BUCKET}"
echo "  CloudFront dist ID:   ${CF_DISTRIBUTION_ID}"
echo "  API Gateway URL:      ${API_GATEWAY_URL}"
echo "  Frontend URL:         ${FRONTEND_URL}"

# ---------------------------------------------------------------------------
# Step 2: Write frontend/.env.production
#
# Clerk key lookup order (first match wins):
#   1. frontend/.env.${ENV}.keys  — per-environment secrets file (gitignored)
#      Create it once:
#        echo "VITE_CLERK_PUBLISHABLE_KEY=pk_test_..." > frontend/.env.dev.keys
#        echo "VITE_CLERK_PUBLISHABLE_KEY=pk_live_..." > frontend/.env.prod.keys
#   2. frontend/.env               — dev fallback (already has pk_test_ key)
#   3. Shell environment           — last resort / CI pipelines
# ---------------------------------------------------------------------------

echo ""
echo "[2/5] Writing frontend/.env.production..."

# Source the per-environment keys file if it exists
KEYS_FILE="${FRONTEND_DIR}/.env.${ENV}.keys"
ENV_FILE="${FRONTEND_DIR}/.env"

CLERK_KEY=""

if [[ -f "${KEYS_FILE}" ]]; then
  echo "  Reading Clerk key from ${KEYS_FILE}"
  CLERK_KEY=$(grep -E "^VITE_CLERK_PUBLISHABLE_KEY=" "${KEYS_FILE}" | cut -d= -f2- | tr -d '[:space:]"' || true)
fi

if [[ -z "${CLERK_KEY}" && -f "${ENV_FILE}" ]]; then
  echo "  Reading Clerk key from ${ENV_FILE} (dev fallback)"
  CLERK_KEY=$(grep -E "^VITE_CLERK_PUBLISHABLE_KEY=" "${ENV_FILE}" | cut -d= -f2- | tr -d '[:space:]"' || true)
fi

if [[ -z "${CLERK_KEY}" ]]; then
  # Last resort: shell environment (useful in CI)
  CLERK_KEY="${VITE_CLERK_PUBLISHABLE_KEY:-}"
fi

if [[ -z "${CLERK_KEY}" ]]; then
  echo ""
  echo "  ERROR: VITE_CLERK_PUBLISHABLE_KEY not found."
  echo "  Create a keys file with your Clerk publishable key:"
  echo "    echo 'VITE_CLERK_PUBLISHABLE_KEY=pk_test_...' > frontend/.env.${ENV}.keys"
  echo "  (This file is gitignored — never committed to the repo)"
  exit 1
fi

echo "  Clerk key: ${CLERK_KEY:0:12}... (truncated)"

cat > "${FRONTEND_DIR}/.env.production" <<EOF
# Auto-generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Environment: ${ENV}
# Do NOT commit this file (it is gitignored).

# API Gateway HTTP API endpoint
VITE_API_URL=${API_GATEWAY_URL}/api

# Clerk publishable key (pk_test_... for dev, pk_live_... for prod)
VITE_CLERK_PUBLISHABLE_KEY=${CLERK_KEY}
EOF

echo "  Written: ${FRONTEND_DIR}/.env.production"
echo "  VITE_API_URL=${API_GATEWAY_URL}/api"

# ---------------------------------------------------------------------------
# Step 3: Build the Vue 3 app
# ---------------------------------------------------------------------------

echo ""
echo "[3/5] Building frontend (npm run build)..."

cd "${FRONTEND_DIR}"
npm run build

DIST_DIR="${FRONTEND_DIR}/dist"
if [[ ! -d "${DIST_DIR}" ]]; then
  echo "ERROR: Build failed — dist/ directory not found."
  exit 1
fi

FILE_COUNT=$(find "${DIST_DIR}" -type f | wc -l | tr -d ' ')
echo "  Build complete: ${FILE_COUNT} files in dist/"

# ---------------------------------------------------------------------------
# Step 4: Sync dist/ to S3
#
# Two sync passes for optimal cache headers:
#   Pass A — hashed assets (/assets/*): Cache-Control: max-age=31536000, immutable
#   Pass B — everything else (index.html, etc.): Cache-Control: no-cache
#
# This matches the CloudFront cache policy (assets cached 1 year, index.html 5 min).
# ---------------------------------------------------------------------------

echo ""
echo "[4/5] Uploading to S3 (s3://${FRONTEND_BUCKET})..."

# Pass A: hashed assets — tell browsers and CloudFront to cache for 1 year
aws s3 sync "${DIST_DIR}/assets" "s3://${FRONTEND_BUCKET}/assets" \
  --profile "${AWS_PROFILE}" \
  --cache-control "public, max-age=31536000, immutable" \
  --delete \
  --exact-timestamps

# Pass B: everything else — no-cache so browsers always revalidate with CloudFront
aws s3 sync "${DIST_DIR}" "s3://${FRONTEND_BUCKET}" \
  --profile "${AWS_PROFILE}" \
  --cache-control "public, no-cache" \
  --exclude "assets/*" \
  --delete \
  --exact-timestamps

echo "  Upload complete."

# ---------------------------------------------------------------------------
# Step 5: Invalidate CloudFront cache
#
# Invalidate /* so edge locations fetch fresh index.html immediately.
# Hashed assets never need invalidation (their URLs change per build).
# ---------------------------------------------------------------------------

echo ""
echo "[5/5] Invalidating CloudFront cache (distribution: ${CF_DISTRIBUTION_ID})..."

INVALIDATION_ID=$(aws cloudfront create-invalidation \
  --profile "${AWS_PROFILE}" \
  --distribution-id "${CF_DISTRIBUTION_ID}" \
  --paths "/*" \
  --query "Invalidation.Id" \
  --output text)

echo "  Invalidation created: ${INVALIDATION_ID}"
echo "  (Propagation takes ~30-60 seconds globally)"

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

echo ""
echo "============================================="
echo "  Deploy complete!"
echo "  Frontend URL: ${FRONTEND_URL}"
echo "============================================="
echo ""
echo "Smoke test checklist:"
echo "  [ ] Open ${FRONTEND_URL} — app loads"
echo "  [ ] Clerk sign-in flow works"
echo "  [ ] Create a niche → API call reaches Lambda"
echo "  [ ] Trigger collection → 202 received, run_id returned"
echo "  [ ] Search ads → results appear"
